package guru.qa.api.dummy.models.post;

import guru.qa.api.dummy.models.user.UserPreview;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class PostPreview {

    private String id;
    private String text;
    private String image;
    private String likes;
    private String tags;
    private String publishDate;
    private UserPreview owner;
}

/**
 * {
 * id: string(autogenerated)
 * text: string(length: 6-50, preview only)
 * image: string(url)
 * likes: number(init value: 0)
 * tags: array(string)
 * publishDate: string(autogenerated)
 * owner: object(User Preview)
 * }
 */
