package guru.qa.api.dummy.models.post;

import guru.qa.api.dummy.models.user.UserPreview;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Post {

    private String id;
    private String text;
    private String image;
    private Integer likes;
    private String link;
    private List<String> tags;
    private String publishDate;
    private String updatedDate;
    private UserPreview owner;
}

/**
 * {
 * id: string(autogenerated)
 * text: string(length: 6-1000)
 * image: string(url)
 * likes: number(init value: 0)
 * link: string(url, length: 6-200)
 * tags: array(string)
 * publishDate: string(autogenerated)
 * owner: object(User Preview)
 * }
 */
