package guru.qa.api.dummy.models.user;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class UserPreview {
    private String id;
    private String title;
    private String firstName;
    private String lastName;
    private String picture;
}

/**
 * {
 * id: string(autogenerated)
 * title: string("mr", "ms", "mrs", "miss", "dr", "")
 * firstName: string(length: 2-50)
 * lastName: string(length: 2-50)
 * picture: string(url)
 * }
 */
