package guru.qa.api.dummy.models.comment;

import guru.qa.api.dummy.models.user.UserPreview;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class CommentPreview {

    private String id;
    private String message;
    private String post;
    private String publishDate;
    private UserPreview owner;
}

/**
 * {
 * id: string(autogenerated)
 * message: string(length: 2-500)
 * owner: object(User Preview)
 * post: string(Post Id)
 * publishDate: string(autogenerated)
 * }
 */
